"use strict";
const assert=require("assert");
const fs=require("fs");
const html=fs.readFileSync(require("path").resolve(__dirname,"../index.html"),"utf8");
assert(html.includes('<script src="draft-journal.js"></script>'),"draft journal script is missing");
assert(html.includes('id="toast" role="status" aria-live="polite"'),"toast announcements are not accessible");
assert(html.includes('id="newBtn">Add question</button>'),"add-question action is ambiguously labelled");
assert(html.includes('id="addBtn" tabindex="-1">Paste AI output</button>'),"AI-output action is ambiguously labelled");
assert(html.includes('id="settingsBtn">Settings</button>'),"advanced actions are not grouped under settings");
assert(html.includes('class="workspace" data-mobile-view='),"writing workspace is missing");
assert(html.includes('id="studyStatus"'),"revision status control is missing");
assert(html.includes('id="homeSearch"'),"writing dashboard search is missing");
assert(html.includes('id="browseBtn" aria-expanded="false"'),"mobile browse drawer control is missing");
assert(html.includes('location.protocol==="https:"'),"secure deployed AI generation is disabled");
assert(html.includes('searchParams.set("q",id)'),"question deep links are missing");
assert(html.includes('routeFallbacks.push(label)'),"OpenRouter compatibility retries are missing");
assert(html.includes('body.max_tokens=body.max_completion_tokens'),"OpenRouter token-parameter fallback is missing");
assert(html.includes('delete body.stream_options'),"OpenRouter stream-metadata fallback is missing");
assert(html.includes('OpenRouter could not find a provider for this request after compatibility retries'),"OpenRouter routing errors are misreported");
assert(!html.includes('no provider endpoint supporting the required JSON mode'),"routing errors still blame JSON mode without evidence");
assert(!html.includes('localStorage.setItem(GHKEY,JSON.stringify(ghCfg))'),"GitHub token may be persisted in localStorage");
assert(!html.includes('b.textContent="Overwrite"'),"unsafe remote overwrite action is present");
const scripts=[...html.matchAll(/<script(?![^>]*type="application\/json")(?![^>]*src=)[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
assert(scripts.length>=2,"expected inline application scripts");
for(const source of scripts) new Function(source);
console.log("HTML scripts parse cleanly");
